version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    container_name: elasticsearch
    environment:
      - node.name=elasticnode01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - estdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  web:
    container_name: web
    build: .
    command: uvicorn app.main:app --lifespan on --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch

volumes:
  estdata:
    driver: local

networks:
  testnetwork:
    name: my-pre-existing-network
    external: true
